project:
  type: website

website:
  description: "Joels blog for Applied Bioinformatics"
  site-url: https://joeltekoniemi.github.io/Applied-Bioinformatics-Blog/ # you must change this appropriately for RSS feeds to work properly
  title: "JT_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JoelTekoniemi
format:
  html:
    css: styles.css
execute:
  freeze: auto
